### ISSUE TITLE
Question: Using access tokens, oauth

### ISSUE THREAD

**Issue by David-Kristek** [slack-samples/bolt-js-slack-connect#3] opened 2023-03-01 21:13 UTC
I am developing a similar slack app using oauth and have a few questions @horeaporutiu and others.  

1. How can we check if user has already gone through the oauth proccess and if not make the app to send him a message with a redirect button?
2.  How is the access token used after the exchange. I know it's stored in the database, but what is the point of it, how is the token used inside the slack bolt js then?
3. How can I use the access token for authenticating third party. I am using third party API and gotta setup a special oauth for my slack up, so my question can I somehow use the access token?

Thanks

**Comment by hello-ashleyintech** [comment] 2023-03-02 15:40
Hi, @David-Kristek! Thanks for your question!

This appears to be a duplicate of https://github.com/slackapi/bolt-js/issues/1756, which has been replied to, so I will close this issue out. Please feel free to submit a new issue if you have any other questions!

**Closed by hello-ashleyintech** 2023-03-02 15:40 UTC
Labels: question
